server:
  port: 4040

spring:
  application:
    name: student-info-system


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: G0p1El61

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost
    port: 6379
    database: 0



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.school.system.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: INFO
    com.school.system: DEBUG


project:
  mysql:
    dump-path: "mysqldump"
    client-path: "mysql"
